--- # Seting up local server
- hosts: nginxserver
  user: deployer
  connection: ssh
  become: yes
  gather_facts: no
  pre_tasks:
  - name: Start time
    raw: date > $HOME/time.log
  roles:
  - setupnginx
  post_tasks:
  - name: End Time
    raw: date >> $HOME/time.log    
